### ISSUE TITLE
Custom Command not working as expected does target add CIDR mask?

### ISSUE THREAD

**Issue by warriorsoul15** [checktheroads/hyperglass#129]
# Custom Commands not working as expected

If I add custom commands for a device I expect them to overwrite the built-in.  But something is going on with the parsing

I have written a routing-protocol agnostic command for IOS that show the route regardless of protocol however when I run it it errors with:

I try passing   10.200.0.0   in the target box without CIDR notation.  and I receive:

"^
% Invalid input detected at '^' marker."

this happens in IOS if you pass a CIDR at the end of the route.

BR-CSW-01#show ip route 10.200.0.0/16
                                                            ^
% Invalid input detected at '^' marker.

Is the system adding a /XX cidr if you dont specify one ?

Reference proper output:

BR-CSW-01#show ip route 10.200.0.0
Routing entry for 10.200.0.0/16
  Known via "ospf 1", distance 110, metric 1000, type extern 2, forward metric 100
  Last update from 10.5.208.22 on TenGigabitEthernet1/1/32, 1w0d ago
  Routing Descriptor Blocks:
  * 10.5.208.22, from 10.5.208.86, 1w0d ago, via TenGigabitEthernet1/1/32
      Route metric is 1000, traffic share count is 1

## Local Configurations

atc_ios_commands:
  ipv4_default:
    bgp_route: "show ip route {target}"
    bgp_aspath: "show ip bgp as-path {target}"
    bgp_community: "show ip bgp community {target}"
    ping: "ping {target}"
    traceroute: "traceroute {target}"
  ipv6_default:
    bgp_route: "show ipv6 route {target}"
    bgp_aspath: "show ipv6 bgp as-path {target}"
    bgp_community: "show ipv6 bgp community {target}"
    ping: "ping6 {target}"
    traceroute: "traceroute6 {target}"
  ipv4_vpn:
    bgp_route: "show ip route {target} vrf {vrf}"
    bgp_aspath: "show ip bgp as-path {target} vrf {vrf}"
    bgp_community: "show ip bgp community {target} vrf {vrf}"
    ping: "ping {target} vrf {vrf}"
    traceroute: "traceroute {target} vrf {vrf}"
  ipv6_vpn:
    bgp_route: "show ipv6 route {target} vrf {vrf}"
    bgp_aspath: "show ipv6 bgp as-path {target} vrf {vrf}"
    bgp_community: "show ipv6 bgp community {target} vrf {vrf}"
    ping: "ping6 {target} vrf {vrf}"
    traceroute: "traceroute6 {target} vrf {vrf}"

| Metric | Value |
| ------ | ----- |
| **hyperglass Version** | **1.0.0-beta.80** |
| **hyperglass Path** | `None` |
| **Python Version** | `3.6.8` |
| **Platform Info** | `Linux-4.18.0-240.10.1.el8_3.x86_64-x86_64-with-redhat-8.3-Ootpa` |
| **CPU Info** | Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz |
| **Logical Cores** | `2` |
| **Physical Cores** | `2` |
| **Processor Speed** | 2.399998GHz |
| **Total Memory** | 8.15 GB |
| **Memory Utilization** | 47.0% |
| **Total Disk Space** | 52.58 GB |
| **Disk Utilization** | 14.2% |

## Client

- OS & Version: 
- Browser: 

### Smartphone Details (if applicable)

- Device: 
- OS: 
- Browser:

**Comment by checktheroads** [comment]
Hi there,

Sorry for the delay, I was traveling for work and then took some extra time off afterward, but now I'm starting to catch up!

This is actually expected default behavior, explained [here](https://hyperglass.io/docs/adding-devices#ipv4). TLDR, you can add `force_cidr: false` to the device's VRF definition (per address-family), for example:

```yaml
# devices.yaml
routers:
  - name: New York City, NY
    nos: cisco_ios
    vrfs:
      - name: global
        default: true
        ipv4:
          force_cidr: false
          source_address: 192.0.2.1
```

Also, I noticed an issue with the command profile you provided (an issue you may or may not run into, but I noticed it in my lab setup) - the `vrf {vrf}` statement needs to come before the `{target}` for IOS's `show ip route` command. For example:

```yaml
# commands.yaml
ios_test:
  ipv4_default:
    bgp_route: 'show ip route {target}'
    bgp_aspath: 'show ip bgp as-path {target}'
    bgp_community: 'show ip bgp community {target}'
    ping: 'ping {target}'
    traceroute: 'traceroute {target}'
  ipv6_default:
    bgp_route: 'show ipv6 route {target}'
    bgp_aspath: 'show ipv6 bgp as-path {target}'
    bgp_community: 'show ipv6 bgp community {target}'
    ping: 'ping6 {target}'
    traceroute: 'traceroute6 {target}'
  ipv4_vpn:
    bgp_route: 'show ip route vrf {vrf} {target}'
    bgp_aspath: 'show ip bgp as-path {target} vrf {vrf}'
    bgp_community: 'show ip bgp community {target} vrf {vrf}'
    ping: 'ping {target} vrf {vrf}'
    traceroute: 'traceroute {target} vrf {vrf}'
  ipv6_vpn:
    bgp_route: 'show ipv6 route vrf {vrf} {target}'
    bgp_aspath: 'show ipv6 bgp as-path {target} vrf {vrf}'
    bgp_community: 'show ipv6 bgp community {target} vrf {vrf}'
    ping: 'ping6 {target} vrf {vrf}'
    traceroute: 'traceroute6 {target} vrf {vrf}'
```

The above works in my lab (CSR 1000V) with the internet routing table in a separate VRF.

Hope this helps!
