### ISSUE TITLE
connecting to linux

### ISSUE THREAD

**Issue by dpskipper** [checktheroads/hyperglass#137]
Using the standard devices.yaml file from the documentation does not work. Can you provide a working example for a linux device?

**Comment by pcfriek1987** [comment]
Not sure what you mean by a Linux device? Do you mean FRR?

**Comment by checktheroads** [comment]
You'll need to use `nos: linux` in `devices.yaml`, and you'll need to [define a command set](https://hyperglass.io/docs/commands#adding-a-custom-command-set). I just used this example and it works perfectly:

```yaml
# devices.yaml
routers:
  - name: Linux Text
    address: <hostname>
    network:
      name: test1
      display_name: Test Network
    commands: linux_test
    credential:
      username: <username>
      password: <password>
    nos: linux
    vrfs:
      - name: global
        default: true
        display_name: Global
        ipv4:
          access_list:
            - network: 0.0.0.0/0
              action: permit
              ge: 8
              le: 24
        ipv6: null

```

```yaml
# commands.yaml
linux_test:
  ipv4_default:
    bgp_route: 'echo "{target}"'
    bgp_aspath: 'echo "{target}"'
    bgp_community: 'echo "{target}"'
    ping: 'echo "{target}"'
    traceroute: 'echo "{target}"'
  ipv6_default:
    bgp_route: 'echo "{target}"'
    bgp_aspath: 'echo "{target}"'
    bgp_community: 'echo "{target}"'
    ping: 'echo "{target}"'
    traceroute: 'echo "{target}"'
  ipv4_vpn:
    bgp_route: 'echo "{vrf} {target}"'
    bgp_aspath: 'echo "{vrf} {target}"'
    bgp_community: 'echo "{vrf} {target}"'
    ping: 'echo "{vrf} {target}"'
    traceroute: 'echo "{vrf} {target}"'
  ipv6_vpn:
    bgp_route: 'echo "{vrf} {target}"'
    bgp_aspath: 'echo "{vrf} {target}"'
    bgp_community: 'echo "{vrf} {target}"'
    ping: 'echo "{vrf} {target}"'
    traceroute: 'echo "{vrf} {target}"'
```
