### ISSUE TITLE
"Default" VRF required or build-ui fails.

### ISSUE THREAD

**Issue by Napsterbater** [checktheroads/hyperglass#29]
## Information

**Describe the bug**
Config is required to have the "default" VRF specified, should be able to have only non default VRFs used/defined.

When running "sudo hyperglass build-ui" you will get this error if a config has no default VRFs.
AttributeError: 'Routers' object has no attribute 'default_vrf'

**To Reproduce**
Create device config with  devices that have no default VRF.

**Expected behavior**
Should be allowed.

**Screenshots**

AttributeError: 'Routers' object has no attribute 'default_vrf'

### Back End
**Server:**
 - OS: Ubuntu 19.10
 - Python Version: 3.7
 - Reverse Proxy: N/A
 - Redis Version:  5.0.5

### Front End

N/A

**Comment by checktheroads** [comment]
Hi,

Can I assume that this is relevant for you because you’re using hyperglass as an internal tool? The main reason this is required (and included with the default example configs) is to make the setup faster and easier on the end user. That, and so that some other reasonable defaults can be set. 

That said, it’s not impossible to remove the requirement, I’d just want to understand the reason to ensure it’s worked around properly.

Thanks!
-Matt

**Comment by 3xh4l3** [comment]
How to use some commands with default VRF definition?

Fore example Ping:

[SUCCESS] 20200617 02:05:30 | hyperglass.api.routes:114 | query → Completed query execution for Query(query_location=router_dc1, query_type=ping, query_vrf=default, query_target=1.1.1.1)

And my Cisco IOS XE router returns that:

`^
% Invalid input detected at '^' marker.`

I assume that no `default` VRF present on the box. 

Here is config:

```
---
# Credentials
credentials:
  - credential: &credential1
      username: hyperglass 
      password: Hyperglass@2020 

# Routers
routers:
  - name: router.dc1 
    address: 10.226.251.9
    network: 
        name: somecity 
        display_name: Somecity, ASXXXXX
    credential: *credential1
    display_name: ROUTER.DC1 (4900M)
    port: 22
    nos: cisco_ios
    vrfs:
      - name: default
        ipv4:
          source_address: 100.100.100.100
    proxy: null
```
But I not need to use any vrf on my router. What should I do?
