### ISSUE TITLE
Devices.yaml not reading display_name correctly.

### ISSUE THREAD

**Issue by jbndis1** [checktheroads/hyperglass#40]
When I try to run hyperglass build-ui or hyperglass run I get the error "hyperglass.exceptions.ConfigInvalid: The value field "network: display_name" is invalid: field required"

 - OS: Ubuntu 18.04
 - Python Version: 3.6.9

Attached is my devices.yaml

![image](https://user-images.githubusercontent.com/40966501/82183685-6e487900-98b4-11ea-839b-eff8c5ebd8bd.png)

**Comment by checktheroads** [comment]
Hi there,

At first glance, I believe this is a syntax error, probably stemming from a documentation error :) Can you change your network definition from this:

```yaml
routers:
  - name: core1
     network:
      - name: primary
         display_name: AS213242
```

To this:

```yaml
routers:
  - name: core1
     network:
         name: primary
         display_name: AS213242
```

That `-` is making it a list/array, which is incorrect. I confirmed that’s how it is in the docs, but not how the code accepts it. Please let me know if that’s resolves the issue, and I’ll fix the docs.

Thanks!
-Matt
